name: Deploy to gh-pages

on:
  push:
    branches:
      - master
      - deploy
  workflow_dispatch:

jobs:
  deploy:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm ci
          npm i -g gh-pages
      - name: config
        run: |
          git config --global user.email mukeshgurpude02@gmail.com
          git config --global user.name "Mukesh Gurpude"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - name: Build and Deploy
        run: |
          npm run build
          gh-pages -d build
